### ISSUE TITLE
Selection box on icon kit does not show up on all devices

### ISSUE THREAD

**Issue by muzikbike** [GDColon/GDBrowser#100]
Shows up fine on PC, getting nothing on ipad (but all other functionality is there).
![AE68742A-8BD2-4DCB-96AD-AF3DA2778CC0](https://user-images.githubusercontent.com/52297970/83702185-d365d380-a603-11ea-9f3b-96921bf4332f.png)
![09412490-3C3C-451B-8107-98845281F8C0](https://user-images.githubusercontent.com/52297970/83702192-d9f44b00-a603-11ea-930d-b4d869edbaac.png)

**Comment by GDColon** [comment]
Not all browsers support border images
