### ISSUE TITLE
Carry across paths from gmd.gg

### ISSUE THREAD

**Issue by etstringy** [GDColon/GDBrowser#101]
Currently gmd.gg redirects to gdbrowser.com, but however, the path is not carried across. I imagine this would probably be a single line of nginx configuration, or a really easy thing to do.

This would open up the possibilities for links like following:
gmd.gg/10565740
gmd.gg/u/Colon

**Comment by GDColon** [comment]
yeah i should probably do this at some point. noted

**Comment by GDColon** [comment]
Done!
