### ISSUE TITLE
messages api on "Error fetching messages!"

### ISSUE THREAD

**Issue by RedLime** [GDColon/GDBrowser#103]
why that return "Error fetching messages!" error?
```
page = 0
accountID = 13362526
password = bruh
```
I have set the parameters correctly, and I have also confirmed that the password or ID of the account is correct, but seems this error.

**Comment by RedLime** [comment]
now it is solved with NOT CHANGES. is it RobTop's server problem?

**Comment by RedLime** [comment]
https://imgur.com/a/zOt78oI
and cannot login account on GD Browser.

**Comment by GDColon** [comment]
Blame RobTop. Looking into this.
