### ISSUE TITLE
Robot icon bugs

### ISSUE THREAD

**Issue by Conlinkin** [GDColon/GDBrowser#107]
Three robots have some rendering issues with either misplaced legs or faces and/or have color issues.

This robot has the face too low:
![Screenshot_20200923-233148_Chrome](https://user-images.githubusercontent.com/24375555/94105303-3a4b0a80-fdf6-11ea-9aaa-f096429f3c96.png)

This robot has the legs not being attached to the face:
![Screenshot_20200923-233220_Chrome](https://user-images.githubusercontent.com/24375555/94105389-5fd81400-fdf6-11ea-8769-fd06b00aa9a9.png)

This robot has the color on the legs not being in the leg and looks like it's clipping out of it:
![Screenshot_20200923-233237_Chrome](https://user-images.githubusercontent.com/24375555/94105417-6e263000-fdf6-11ea-90bc-a21f6c02907f.png)

**Comment by GDColon** [comment]
I probably just got the formula for building the robots slightly wrong. I spent hours and hours trying to get as close as possible, so unfortunately I don't think I can do any better
