### ISSUE TITLE
Analyzing level bugs

### ISSUE THREAD

**Issue by Conlinkin** [GDColon/GDBrowser#108]
I've noticed two small bugs whenever you analyze a level.
1. The OBJ color appears twice on levels if the OBJ color was changed from default settings. (Example screenshot is taken from Ocular Miracle)
![Screenshot_20200923-232445_Chrome](https://user-images.githubusercontent.com/24375555/94105713-1f2cca80-fdf7-11ea-8c47-ea712c40f51c.png)

2. The colors BG, G, G2, Line, and OBJ appear if they aren't changed from their default settings, but 3DL doesn't appear if it isn't changed.
![Screenshot_20200923-232326_Chrome](https://user-images.githubusercontent.com/24375555/94105958-aaa65b80-fdf7-11ea-84f0-995f5a21de38.png)

**Comment by GDColon** [comment]
Double obj is definitely a bug, and missing 3DL is because it's not saved in the level data
