### ISSUE TITLE
Leaderboard position misalignment bug

### ISSUE THREAD

**Issue by Conlinkin** [GDColon/GDBrowser#109]
This might be a mobile only issue, but I figured I should report it just in case.
In the global leaderboards and the level leaderboards, the icons and numbers get misaligned the farther you go down. This especially becomes a problem after 200.
![Screenshot_20200923-235437_Chrome](https://user-images.githubusercontent.com/24375555/94106348-74b5a700-fdf8-11ea-9144-114900de1f00.png)

**Comment by GDColon** [comment]
Aware of this, it's due to shitty hardcoding. Gonna leave this issue active since I really gotta get around to fixing it

**Comment by 101arrowz** [comment]
hey i wonder what would happen if you used flexbox

**Comment by GDColon** [comment]
Fixed
