### ISSUE TITLE
Song Issue

### ISSUE THREAD

**Issue by ArrowBlitZ-dev1189** [GDColon/GDBrowser#115]
![Screen Shot 2020-10-21 at 10 17 21 AM](https://user-images.githubusercontent.com/58670749/96733049-04faf380-1387-11eb-8803-ab5530fc01eb.png)
![Screen Shot 2020-10-21 at 10 17 35 AM](https://user-images.githubusercontent.com/58670749/96733063-07f5e400-1387-11eb-8d22-d0855cc25a1c.png)

It doesn't show the correct song at all times. Not a website-breaking bug, but needs to be fixed.

**Comment by GDColon** [comment]
![image](https://user-images.githubusercontent.com/56617416/96806779-f93d1a80-13e2-11eb-8d84-b48d30d13c0c.png)
What did you search? I can't reproduce it.

**Comment by ArrowBlitZ-dev1189** [comment]
Sorry, it might have just been my browser or something. It's been replacing random songs with Stereo Madness.

I did it by clicking Demon filter (Regular Demon, not medium demon), and then clicking Awarded (Icon has a star)

**Comment by GDColon** [comment]
Hmm, it's working totally fine on my end. Still can't reproduce unfortunately.
