### ISSUE TITLE
Space characters gets collapsed into one

### ISSUE THREAD

**Issue by tildeman** [GDColon/GDBrowser#118]
I guess this is an HTML feature to not mistakenly output multiple whitespace characters that are meant to be used for pretty-printing, but anyway a level by BekID1442 named "absolute&nbsp;&nbsp;zero" is displayed in GDBrowser incorrectly as "absolute zero".

Geometry Dash:
![absolute](https://user-images.githubusercontent.com/59699056/97801258-e7bf0280-1c6d-11eb-9b3c-c21e5eba21d0.PNG)
GDBrowser:
![zero](https://user-images.githubusercontent.com/59699056/97801274-03c2a400-1c6e-11eb-919f-d21c41b4c232.png)
One possible approach is to replace every space character with a no-break space. In PHP there is a function called str_replace that replaces occurences of a substring with a replacement string, but I don't know if there is a Node.js equivalent of that function.

**Comment by 101arrowz** [comment]
It's not too difficult in Node.js. `html.replace(/ /g, '&nbsp;')`. I think he's already doing some replacement elsewhere for `&lt;` and all, so this should be an easy fix.

**Comment by GDColon** [comment]
Fixed by adding `white-space: pre` to some spots. It's already live on GDBrowser but it's not important so I won't make a commit specifically for it.
