### ISSUE TITLE
bro, you missed on Boolean reverse check.

### ISSUE THREAD

**Issue by RedLime** [GDColon/GDBrowser#120]
![image](https://user-images.githubusercontent.com/25276450/98336836-fbda7980-204a-11eb-975f-77c03c7f6f6e.png)
This is api/profile.js file, and the Boolean for Number() was reversed (before was not ! checked). I think you need to fix it.

**Comment by GDColon** [comment]
nah, current code is correct

**Comment by RedLime** [comment]
> nah, current code is correct

but, find profile by playerID is not work.

**Comment by GDColon** [comment]
account ID is the default now since it's what gd mainly uses, use ?player if you wanna search by player id

**Comment by RedLime** [comment]
> account ID is the default now since it's what gd mainly uses, use ?player if you wanna search by player id

oh, i see! 😊
