### ISSUE TITLE
the decimal bug

### ISSUE THREAD

**Issue by gdhpsk** [GDColon/GDBrowser#124]
For some reason if I say 99.99, it says I have to get 100.99, but you can't really. its just a bug I found idk if it has to be fixed but mabye make the inputs like number only like lets say if someone does put a decimal give an error

**Comment by GDColon** [comment]
What are you referring to here

**Comment by gdhpsk** [comment]
So you know how you type your % ion the text box? Well apparently you can
also type decimals as well, and mabye you could fix it

**Comment by GDColon** [comment]
What text box are you talking about? I have no idea what you're trying to say

**Comment by gdhpsk** [comment]
Here’s a vid actually

---------- Forwarded message ---------

**Comment by GDColon** [comment]
You haven't attached anything.
Closing this issue since you can't seem to make a proper bug report.
