### ISSUE TITLE
LogIn always fails

### ISSUE THREAD

**Issue by unico-de** [GDColon/GDBrowser#126]
I can't login to gdbrowser with my gd acc ;-;
<img width="834" alt="Screen Shot 2020-12-02 at 10 13 35 AM" src="https://user-images.githubusercontent.com/75379747/100891352-2c190a80-3487-11eb-9ed8-716bed89bc11.png">
but I can login with the exact same account user/pass on gd app?
i try to use message reading on gdbrowser but on the login it says error fetching profile
;-;

**Comment by GDColon** [comment]
This is an issue on Rob's end, it seems like there's weird rate limits or something
