### ISSUE TITLE
Esc Feature Crashes Site

### ISSUE THREAD

**Issue by unico-de** [GDColon/GDBrowser#134]
May be a small bug, or isn't that bad, but ill still say it,

Escape key makes you go back a page, however, using that feature when going to a page, will crash the site. Example, going to search and right after clicking "Search", you use escape key. Then, the site address will display "gdbrowser.com/search" but the webpage itself will be fully black.

**Comment by GDColon** [comment]
This sseems to be an issue on your end. What browser are you using?
