### ISSUE TITLE
Star icon bugged in level leaderboards

### ISSUE THREAD

**Issue by QuaKe8782** [GDColon/GDBrowser#136]
When you look at the leaderboards for a level, the coin icons display incorrectly. Or at least I think they do. Not sure if having a line in place of a coin is intentional.

**Comment by GDColon** [comment]
They look fine on my end, can you post a screenshot

**Comment by QuaKe8782** [comment]
![image](https://user-images.githubusercontent.com/67868381/109425573-cafac780-79e0-11eb-9ac4-9c656258148a.png)

**Comment by QuaKe8782** [comment]
My browser is Microsoft Edge Chromium.  I tried on Firefox and got the same result.

**Comment by QuaKe8782** [comment]
For reference, here's what it should look like.
![image](https://user-images.githubusercontent.com/67868381/109425670-42305b80-79e1-11eb-9bac-f2ed4dd7b1a4.png)

**Comment by GDColon** [comment]
Fixed, thank you! Just the result of a change I made to regular leaderboards a few days ago
