### ISSUE TITLE
Global ranking on leaderboards is off by 1

### ISSUE THREAD

**Issue by QuaKe8782** [GDColon/GDBrowser#137]
Pretty self explanatory.
![image](https://user-images.githubusercontent.com/67868381/109425810-2bd6cf80-79e2-11eb-97e6-746b42da580e.png)
![image](https://user-images.githubusercontent.com/67868381/109425816-32fddd80-79e2-11eb-94f8-1977e3ed3ad9.png)

**Comment by GDColon** [comment]
This occurs in regular GD as well.
