### ISSUE TITLE
2.2 Icon?

### ISSUE THREAD

**Issue by CodeGuy92** [GDColon/GDBrowser#139]
Since you've added the new swingcopter tab from 2.2 in the icon kit... why not also add the new twitch icon?

**Comment by ShadowbreakerGD** [comment]
Nice idea, but I’m not colon. Nor am I big brain. So I can’t add it. I cant even do it myself and make a pull request... smol brain. ¯\_(ツ)_/¯

**Comment by GDColon** [comment]
Don't think I'm going to add one, mainly because it would just confuse people.
"Huh how do I unlock this icon"
"Why don't you add the other 2.2 icons"
etc etc, not worth it so i think i'll just wait until they're officially released

**Comment by CodeGuy92** [comment]
What about the swingcopter...
@GDColon
