### ISSUE TITLE
Spaces in comments and profile posts don’t work for iOS

### ISSUE THREAD

**Issue by ShadowbreakerGD** [GDColon/GDBrowser#142]
When you try to use the space bar when posting a comment or profile post, it puts the space then quickly deletes it. Making your comment look like this:

![B14575FA-2570-45EC-BB8B-4F76A6519712](https://user-images.githubusercontent.com/78216950/114315491-35695200-9acd-11eb-907a-03965ee46ddb.png)

It’s a strange bug, but I thought I would mention it, just in case you fix it one day.

**Comment by GDColon** [comment]
It's just an ordinary textbox

**Comment by ShadowbreakerGD** [comment]
I found a workaround by copying text into the text box so I’m good now. :)
