### ISSUE TITLE
Official Song 0 exists but it's not in GDBrowser

### ISSUE THREAD

**Issue by ManosSef** [GDColon/GDBrowser#149]
When I hack my Geometry Dash with Cheat Engine to change the song to 0, "00: Practice: Stay Inside Me" appears. It is impossible to select it in GDBrowser, though.

**Comment by GDColon** [comment]
I've already accounted for Stay Inside Me in the [list of songs](https://github.com/GDColon/GDBrowser/blob/master/misc/music.json), but it's not included because nothing happens when you search for levels with the song
