### ISSUE TITLE
/api/profile/* returns Unverified users as nonexistant users

### ISSUE THREAD

**Issue by CompanionCube** [GDColon/GDBrowser#153]

**Comment by GDColon** [comment]
Can you explain what you mean?

**Comment by CompanionCube** [comment]
> 
> 
> Can you explain what you mean?

I have a username checker using /api/profile/ for checking names, however unverified users return as untaken accounts.

**Comment by GDColon** [comment]
Hm, can you give an example of this? Unverified users should never have profiles, and even if they did you can just check if they have an account ID or not

**Comment by CompanionCube** [comment]
> 
> 
> Hm, can you give an example of this? Unverified users should never have profiles, and even if they did you can just check if they have an account ID or not

Unverified users and nonexistent users both under the API return -1 which is a bit of a conflict when the way it finds usernames is by checking if it returns -1.

**Comment by GDColon** [comment]
Oh, I understand what you mean
Nothing can be done about this, as unverified users do not have profiles assigned to them. There is no way to search for unverified users using the GD servers
