### ISSUE TITLE
Add an option to customize the texture

### ISSUE THREAD

**Issue by CodeGuy92** [GDColon/GDBrowser#156]
Please
![gamesheet04](https://user-images.githubusercontent.com/79767244/124584226-aade8780-de5c-11eb-9d09-667278ed3a7d.png)

**Comment by GDColon** [comment]
This is extremely hard to do, it's not as simple as just adding a new spritesheet

**Comment by tildeman** [comment]
Rather than thinking about images, think about stacked linear gradients. It makes the problem a lot easier to solve.
A while ago I did a button template (Link: [https://geometry-dash-fan-ideas.fandom.com/wiki/Template:Button](https://geometry-dash-fan-ideas.fandom.com/wiki/Template:Button)) as an alternative to using MS Paint to paste the button image and forget which Pusab to choose from.
Maybe this will help you (I drew the terrible rollerskate using GIMP):
`<div style="border: white 5px solid;float:left;box-sizing:border-box;width:270px;height:270px;">
		<div style="border: black 4px solid;box-sizing:border-box;width:100%;height:100%;background:linear-gradient(to right,#447710,#447710) 100% 240px no-repeat,linear-gradient(to right,#98fe33,#45ab12) 100% 120px no-repeat,linear-gradient(to right,#cbff55,#68cd12) 100% 0 no-repeat;text-align:center;padding-top: 10px;">
			<img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAZAAAAGQCAYAAACAvzbMAAABhGlDQ1BJQ0MgcHJvZmlsZQAAKJF9kT1Iw0AcxV9TtSIVBzuIOkSoThZERR21CkWoEGqFVh1MLv2CJg1Jiouj4Fpw8GOx6uDirKuDqyAIfoC4uTkpukiJ/0sLLWI8OO7Hu3uPu3eAUC0yzWobAzTdNhOxqJhKr4qBV3RgAH5MY0hmljEnSXF4jq97+Ph6F+FZ3uf+HN1qxmKATySeZYZpE28QT23aBud94hDLyyrxOfGoSRckfuS6Uuc3zjmXBZ4ZMpOJeeIQsZhrYaWFWd7UiCeJw6qmU76QqrPKeYuzViyzxj35C4MZfWWZ6zQHEcMiliBBhIIyCijCRoRWnRQLCdqPevj7Xb9ELoVcBTByLKAEDbLrB/+D391a2YnxelIwCrS/OM7HMBDYBWoVx/k+dpzaCeB/Bq70pr9UBWY+Sa80tfAR0LMNXFw3NWUPuNwB+p4M2ZRdyU9TyGaB9zP6pjTQewt0rdV7a+zj9AFIUlfxG+DgEBjJUfa6x7s7W3v790yjvx+ifnK6ouaJSgAAAAZiS0dEAAAAAAAA+UO7fwAAAAlwSFlzAAAuIwAALiMBeKU/dgAAAAd0SU1FB+UGGwQjEsgcq1oAAAAZdEVYdENvbW1lbnQAQ3JlYXRlZCB3aXRoIEdJTVBXgQ4XAAAMyUlEQVR42u3dv44kVxUH4HN7xgsyq5VIDAmSCSBGgg02QDIkCIHkgIwAiSfwSCACXoAAguEFeASEkBNEAJkDIp7ABASIEJkA450i2F3JmJlhuv6ee8/3SU4QszP3V9X1q1PV1R0BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQJeaCG412RYADlpHloJtBCgQhWF7AYx4QJpsNwAHIoWhTAAHH8VhWwIOOorDdgXo6ECjOBQK4MCiOGxvYCQn5VHK9PK/34gCGKlAJuWxm7cj4v2I+LoogLmyXNJIXRzX19v++1dXhy7vJxHxcy8FoLcCSVEcWxfEjEL5XUR8a8df+ZeI+H5EvOclAWQvkF9ExI8ql8SZhfJ+RHyx0EQKKJBb/TAifqUcZpeJEgFKFsiql6wqFcctRfK3iPi8IgEqFIjy2KZIPoiIx0oEGLVA1iqPv19fxxs2251l8jwiLlb8J/8YEd+QLHBUgaxSHiaOs4pkTb+OiO9JFdi7QBaXh+JIUSR/joivSBTookAUR6oSeR4R346I30sU2KNAlMdYRfLTiPiZJAEFokjO9deI+IIEgVfSfRqv8kib76OI+JwEga0LZNb0oTx2LZEPzvyxNyLim9ID0k0gymP3vB/PKJFLyQFbFojv9OirRM7xptSAdBMIXUx+P5AYsFWBmD7GLpEnEfFZiQEmEM71RkR8RwxAqgI5+GtdTSEPn0J8pAlgAmGWr4oASFcgppAuvCkCYO0CcQO9ToF8WQxAuktYppAucvdEOpDzHsjVlSJJ7jMiAFLfRFciaXP+mtSA9O/CUiIp8/2S5IA1vw9k85voPnAxVTm/HRG/lSIokC4KRJGkmuqaJEGBdFcgiuTQ4lAgwHEF8qf3Ip4+UyidFocCAY4tkIhtSkTZbF4cCgQ4vkCOLpHRSmfnd6wpEFAgxxZIbyWCAgFeOOQ5kE8WxicLhS747DNQIDkoEQAFsqhEFAmAAlEknZE5cI7LHg5obrIrDkCBLD7AKRPFASgQU4nSABTI8QdChaI4AAWy+QGyQtnsVBhTeKAQyjrs03h7OyPupXTWyPXMtSoQMIEwUuEBbO0kAgAUCAAKBAAFAoACAQAFAoAC4UC+WAoUCAAoEBbw0CSgQABQIAAoEAAUCAAKBAAUCDvzLAgoEHjBW3kBBQKAAgFAgQCgQABQIACQvUCePhM+gAIBQIHATB4mBAUyWxMngAIBT6MDuxaIKQRAgQCAAgFAgQCgQABQIBCeBQEFAq94Ky+gQABQIAAoEAAUCAAKBAAUCAAKBAAFwrA8TAgKBAAUCAt4Gh1QIAAoEAAUCAAKBAAFAgAKhJ15FgQUCLzgrbyAAgGg/wJ5+swGAFAgACiQhZpYARQIANzqUgRsxFt56YErJgoEYJUTHYWiQAAWF8rJNH0/90B4MA8TUszNy/8UiAIBWDSZKBIFAqBIFAi7cxkLFIkCAVAkCgRTCCQpklJlokBQImAqUSDsXyKKBO4tkqG1o4NzAAKOsPPXSQz5hLsCAZTJfmUyVJEoEIB9C2WYEnEPBOCWE9sNT26HuTdiAgE4ZirpfhIxgQAcc7L7BwUCUKhEViySt3ovEZewAGZa8bJWl5ezTCAAx08kXd5YVyAAKxRJxRJRIAB5ppGuSkSBAOSaRropEQUCoEQUCIASUSAASkSBACiREacQBQJgElEgAAOWSNop5PAC2flbwQB6LJGUn5m1VYE0uwrAaiXylgkEgLklku5SlgIBQIEAmEIUCAAmEABWnEIUCAAKBID9XCgQAOZ4rkAA6JoCAThQzzfSFQgACgSA/VyKIK/7Pql45G86q7juqtva+vu25afmPviRezvIw15II+dXcd1Vt7X1L84izaedpygQJbLO96L0mGHFdVfd1tY/XoG4BzLIC2rNf8e6rdn6ydBkLmMd9CLInGfFdVfd1tZvAqGzF1TmM7SK6666ra1/fN6Fldz19f/+b1dX1m3N1s/xXMJKeEZ22wvpLv/vBZYp14rrrrqtrX/TKcolrKrWfEE95P+fZbyvuO6q29r661AgyUf4LX/Ouq3Z+lEgA0wfS18Y9/380WdmFddddVtbvwKhk7Ox3s/OKq676ra2fgUCAPkKZPTRM/NlJOu2Zr8fE0jhkb630b7iuqtua+tXIHOd9X5lZw4ACgQABbLvFAKAAgFAgbCVtT8srpcPn6u47qrb2voVCAsd/UFvR/3+iuuuuq39fgUCAH0WSMW38q41ile9pNHTuqtua+tXIGw4Wi99Qdz385kvKYy67qrb2voVyBa8lXfDs6rez8YqrrvqtrZ+BcJGZ2ZzXiC9fEtbxXVX3dbWX8eek4Gvt/2Yh97rWfI90T1+xemI6666ra1//YwOOG73VyAVSmSPNwv0XCAjrbvqtrb+8QvEJayk4/2oL6iK6666ra1/fHs3mSlk4zO0njKruO6q29r6TSBDjr4jnaH19oKquO6q29r6TSCmkKSlOUJGFddddVtb/zgTyFF/iBJZuFONnEnFdVfd1tavQBQIQMECOeoeiCfTATrnbbwAKBAAFMh/qfgR7wAKBAAFsjI30gEUCAAKJCn3QQAUyMe5jAWgQAA4V89XV06CBqDEBKJEABTIK+6DACgQUwiAAkk+hSgRoHe9H8cyTSAuZQEoEO0NsIEfKxBTCFDcCCfAWQ/YvvIWUCDJj9mnwhsCQHkMWCDelQUoj+QyTyDuhwDKI/HxMPtBeprzQ+6JAMqj9gQyOziXs4BByiO1kw0GkPZYlPoqUQ8F4l4I4ETWwXkR90OASuWR/vjc0yUskwigPBSIERJwzOn9ZPmys23TYualLIAOTla7utLS82Uhn5cFKA8FokSAssXR7bG4VIEoEyBZcXR9HC5bIIoEOLg4FMgIJaJUAOWhQBQJkL00Rjn2DvNw3uZv7VUmoDgcdwddSOz0fIgiAYXhmGsCUSSgNBxrKy+qRUweTQccY/fX9WdhPWon5QFoDgVyvg+nG3spkNIUEZ9up6HPccs/SAiw5QF2GngYKfNhigCOs+vq8hLWRbRF5fHOu/ZoYLf2mAZeW63p477y+OV37eyAY+3QE8hWk8c775pOgPOPHVpx8OljyQ5gMgGlscKxYLgpRIEoEeCM48SCY8FwBdLVd6Kfok03B92PerVjKRKoVRgrnq1Pk8/COvSPnfXkeU/XL7c4u5Gb3OSWP7cedXUT3YMfcpOb3FAgQ46oR1r6bIzc5Ca3/nJTIA/05HTpxOYed90bkpvc5JY/t151cz3uItr0/Mzwez2rWfP6qtzkJrf8uZlANvbclVW5yU1uKBAAFAgACgQAFEjXbws88m+Xm9zkNv7frkAAUCBb6Pkzq4782+UmN7mN/7crEAAUyENctmZryU1uckOBzNgxw455nyY3ucmt29wUyMYunNnITW5yQ4HM8c+b52fvmZVucrU7zm3kJje55c9NgbCKuS+mx6cLuclNbnJTIHe3N3f5x81HTW5yk1u/uSmQgc4UTEIykJvcGKhAXh98bN7q+wXkJje55c9NgWxszg06Zzdyk5vcUCBjVvjCF0+Tm9zkNkxujsf7mPW1Z1k/PXPhmVeTm9zkNlRuJpCMrZdxRN7zb5Kb3OQ2zt+kQOaPH82OcP5rVG5yk1tX57wKJOMWybJzHvF3yE1ucjN9lC+QaWGrH71TLP39cz/1VG5yk1v+3IxW+/zx07Tw39j7ht2KL4gmN7nJbdzcFMhuw0gfO2eynVJucpOb8lik+48yuVhhG+0xJq/1O5rc5Ca3MrmZQPZZxOIReYuznLV3+BbLrynLTW5y6ys3BbKPaYt/9NwddeOzpCY3ucmtZG4KpNcSuWtn3fkdIk1ucpNb6dwUyCglsqfL1uKjaWpyk5vcyueWynDfB/KpdhpsA+2zU8pNbnLLn5sC2di/pps2ys552VrcxD47pdzkJrf8uSmQnXbO6Pzy3JPT5e5nNHKTm9zy55bJ8At/1E7Th9NNVxskw1sA5SY3ueXPTYHs4LXWpn9Pk51SbnKTm/JQILMXm3n3bHKTm9zk1pNTpcVOEe211lLtAS8/4qHJTW5yk5sJpLtOkb3c5CY3x0gTyLydo73eLvbcE9sAO6Xc5CY3BHRLIFtcf21yk5vc5KZACrmINt28nJ6nM8JsUffBIrnJTW4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwEv/AQioQAu6aIGsAAAAAElFTkSuQmCC" style="width: 180px;height:180px;">
			<div style="font-family: Pusab, Arial; font-size: 36pt; color:white; text-shadow: 2px 2px #000, 2px -2px #000, -2px -2px #000, -2px 2px #000, 3px 0 #000, -3px 0 #000, 0 3px #000, 0 -3px #000; line-height: 1;">A button</div>
		</div>
	</div>`
