### ISSUE TITLE
Don't think I'm going to add one, mainly because it would just confuse people.

### ISSUE THREAD

**Issue by CodeGuy92** [GDColon/GDBrowser#157]
> Don't think I'm going to add one, mainly because it would just confuse people.
> "Huh how do I unlock this icon"
> "Why don't you add the other 2.2 icons"
> etc etc, not worth it so i think i'll just wait until they're officially released

_Originally posted by @GDColon in https://github.com/GDColon/GDBrowser/issues/139#issuecomment-797843620_

If you won't add this, then why did you add the swingcopter?

**Comment by GDColon** [comment]
There's only one swingcopter confirmed, and it's the only one I could get in high quality. There's too many confirmed 2.2 icons and if I try to add them they'll either be low quality or people will just ask why [x] icon is missing
