### ISSUE TITLE
Make the GDBrowser API more friendly

### ISSUE THREAD

**Issue by newtykins** [GDColon/GDBrowser#159]
Perhaps we could make the GDBrowser API more friendly across the board? Things like difficulty IDs are not user-friendly and I believe some parameters could be altered or removed and others could be added to make user experience more smooth. I'd be willing to put towards large contributions to this cause, I just wanted to gauge interest and this repository does not have a discussion tab!

**Comment by Reper2** [comment]
Yeah true

**Comment by GDColon** [comment]
Oohh yeah this could be a good idea, especially since I was pretty lazy with lots of parts. Mainly just never saw a reason to clean things up since it already runs somewhat fine and changes would just break existing projects. But yeah if you wanna help out that would be greatly appreciated!

**Comment by Reper2** [comment]
Or even make it possible to see previews of what levels would look like in the future that haven't been uploaded/created yet?

**Comment by Reper2** [comment]
What code language is the level API?

**Comment by GDColon** [comment]
If you can't figure out what coding language is being used you probably shouldn't be on GitHub

**Comment by Reper2** [comment]
…
I just forgot…
I don’t recognise every code language off the top of my head…

**Comment by Reper2** [comment]
I meant the code language for the response in level API

**Comment by Reper2** [comment]
Like the code language of this:

{
  "name": "Nine Circles",
  "id": "4284013",
  "description": "Easy",
  "author": "Zobros",
  "playerID": "957447",
  "accountID": "2379",
  "difficulty": "Hard Demon",
  "downloads": 24347516,
  "likes": 1597603,
  "disliked": false,
  "length": "Long",
  "stars": 10,
  "orbs": 500,
  "diamonds": 12,
  "featured": true,
  "epic": false,
  "gameVersion": "2.0",
  "editorTime": 0,
  "totalEditorTime": 0,
  "version": 5,
  "copiedID": "0",
  "twoPlayer": false,
  "officialSong": 0,
  "customSong": 533927,
  "coins": 3,
  "verifiedCoins": true,
  "starsRequested": 0,
  "ldm": false,
  "objects": 0,
  "large": false,
  "cp": 2,
  "difficultyFace": "demon-hard-featured",
  "songName": "NK - Nine Circles",
  "songAuthor": "Rukkus",
  "songSize": "7.76MB",
  "songID": 533927,
  "songLink": "http://audio.ngfiles.com/533000/533927_NK---Nine-Circles.mp3"
}

**Comment by Reper2** [comment]
Nvm I figured it out!

**Comment by newtykins** [comment]
If I were to design a new API ofc I'd run it under a v2 endpoint for backwards compatibility it shouldn't be too much of an issue!

**Comment by newtykins** [comment]
> Like the code language of this:
> 
> {
>   "name": "Nine Circles",
>   "id": "4284013",
>   "description": "Easy",
>   "author": "Zobros",
>   "playerID": "957447",
>   "accountID": "2379",
>   "difficulty": "Hard Demon",
>   "downloads": 24347516,
>   "likes": 1597603,
>   "disliked": false,
>   "length": "Long",
>   "stars": 10,
>   "orbs": 500,
>   "diamonds": 12,
>   "featured": true,
>   "epic": false,
>   "gameVersion": "2.0",
>   "editorTime": 0,
>   "totalEditorTime": 0,
>   "version": 5,
>   "copiedID": "0",
>   "twoPlayer": false,
>   "officialSong": 0,
>   "customSong": 533927,
>   "coins": 3,
>   "verifiedCoins": true,
>   "starsRequested": 0,
>   "ldm": false,
>   "objects": 0,
>   "large": false,
>   "cp": 2,
>   "difficultyFace": "demon-hard-featured",
>   "songName": "NK - Nine Circles",
>   "songAuthor": "Rukkus",
>   "songSize": "7.76MB",
>   "songID": 533927,
>   "songLink": "http://audio.ngfiles.com/533000/533927_NK---Nine-Circles.mp3"
> }

Do you mean how does RobTop's API output this data that GD Browser has to parse?

**Comment by Reper2** [comment]
> > Like the code language of this:
> > 
> > {
> >   "name": "Nine Circles",
> >   "id": "4284013",
> >   "description": "Easy",
> >   "author": "Zobros",
> >   "playerID": "957447",
> >   "accountID": "2379",
> >   "difficulty": "Hard Demon",
> >   "downloads": 24347516,
> >   "likes": 1597603,
> >   "disliked": false,
> >   "length": "Long",
> >   "stars": 10,
> >   "orbs": 500,
> >   "diamonds": 12,
> >   "featured": true,
> >   "epic": false,
> >   "gameVersion": "2.0",
> >   "editorTime": 0,
> >   "totalEditorTime": 0,
> >   "version": 5,
> >   "copiedID": "0",
> >   "twoPlayer": false,
> >   "officialSong": 0,
> >   "customSong": 533927,
> >   "coins": 3,
> >   "verifiedCoins": true,
> >   "starsRequested": 0,
> >   "ldm": false,
> >   "objects": 0,
> >   "large": false,
> >   "cp": 2,
> >   "difficultyFace": "demon-hard-featured",
> >   "songName": "NK - Nine Circles",
> >   "songAuthor": "Rukkus",
> >   "songSize": "7.76MB",
> >   "songID": 533927,
> >   "songLink": "http://audio.ngfiles.com/533000/533927_NK---Nine-Circles.mp3"
> > }
> 
> Do you mean how does RobTop's API output this data that GD Browser has to parse? Or did you mean the language that the output uses? If you meant the latter, it's JSON. If you meant the former, it's a mess - I think there's a link to the example on the GD Browser API documentation

The language the output uses, and I think it is C++

**Comment by Reper2** [comment]
I was browsing through the GD Browser assets folder, and I opened one that made me curious and confused, "mod-extra.png", what is mod extra and where is it used in GD? (what players have this role?)

**Comment by GDColon** [comment]
It's used on private servers for any members that have a mod value higher than 2

**Comment by Reper2** [comment]
Oh. Does that also explain all the extra social icon PNG images in assets
too?

**Comment by GDColon** [comment]
Those are just used for giving credit around the site.
Using GitHub issues probably isn't the best place to ask these questions, if you want to ask more questions I prefer if you just reach me through
- Twitter DMS ([@TheRealGDColon](https://twitter.com/TheRealGDColon))
- Discord DMS (join [GD Programming](https://discord.gg/jEwtDBK
) then DM Colon#0009, I don't take friend reqs)
- Email (therealgdcolon@gmail.com)

Cool to see that you're so interested in the project!

**Comment by Reper2** [comment]
Your welcome! I completely forgot about the credits button!
