### ISSUE TITLE
Add Player ID and Account ID search or link

### ISSUE THREAD

**Issue by Reper2** [GDColon/GDBrowser#162]
It'd be really helpful to be able to search with player ID and account ID or have a URL link that contains the player ID/account ID resulting in the GD profile page the player ID/account ID belongs to.

**Comment by GDColon** [comment]
Unless I'm misunderstanding, this should already be doable. Usernames and IDs are pretty much interchangeable in most cases

**Comment by Reper2** [comment]
Well what am I missing in the URL because I’ve tried a few different ways
but they just come up with ERROR 404 level search results?

**Comment by GDColon** [comment]
gdbrowser.com/u/<accountID>
or
gdbrowser.com/u/<playerID>?player
or
gdbrowser.com/u/<accountID>. (add period to the end to redirect to username)

**Comment by Reper2** [comment]
Ok, thanks Colon!

**Comment by Reper2** [comment]
Hey Colon,

I can’t get the playerID URL to work, I tried entering
gdbrowser.com/u/129383269?repergd2 but it redirected me to a level search!

**Comment by GDColon** [comment]
https://gdbrowser.com/u/129383269?player

**Comment by Reper2** [comment]
I should’ve realised to keep the ?player as it was!
