### ISSUE TITLE
Where is secretStuff.json?

### ISSUE THREAD

**Issue by tzt345** [GDColon/GDBrowser#163]
I can't find it can someone 

```js
Help :(
```

**Comment by Reper2** [comment]
GDColon/GDBrowser/Misc/secretStuff.json

**Comment by tzt345** [comment]
> GDColon/GDBrowser/Misc/secretStuff.json

I can't find it on misc bruh

**Comment by tzt345** [comment]
Issue Resolved 👌

**Comment by Reper2** [comment]
https://github.com/GDColon/GDBrowser/blob/master/misc/secretStuff.json
