### ISSUE TITLE
Empty poison gauntlet is shown 2.2-unlocked GDPS?

### ISSUE THREAD

**Issue by TheTechRobo** [GDColon/GDBrowser#164]
https://22unlocked.gdbrowser.com/gauntlets. Is this a bug or is it on 2.2unlocked's end?

This does not happen on 1.9 GDPS. https://19gdps.gdbrowser.com/gauntlets

**Comment by GDColon** [comment]
This is not a bug with the site, it displays exactly what the servers send. Talk to SMJS if you think it's a mistake.

**Comment by TheTechRobo** [comment]
Alright, sorry for wasting your time :/
