### ISSUE TITLE
Unlisted Levels

### ISSUE THREAD

**Issue by Reper2** [GDColon/GDBrowser#169]
I was serching for my unlisted level on the browser using the level id and it couldn't find anything. I know that in-game you normally have to be friends with the person of the unlisted level, and I'm the creator of the unlisted level. So is there any way to search for unlisted levels on the browser?

**Comment by GDColon** [comment]
Your IP is forwarded to the GD servers, which is also what the servers use to check if you can view an unlisted level or not.
