### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Boss-GamerDEV** [GDColon/GDBrowser#178]
An button in a message preview that lets you download the message with the message content.
Suggestion 2:
Being able to download the output of a analyzed level in like a image file or a txt file.
Suggestion 3:
Being able to download the profile stats of a user as a txt file.

_**I love being able to save things easier, lol**_

**Comment by GDColon** [comment]
isn't that just the api

**Comment by Reper2** [comment]
I had 22 emails thanks to you 2…
