### ISSUE TITLE
Description box overlaps coins

### ISSUE THREAD

**Issue by nolemretaWxd** [GDColon/GDBrowser#181]
![image](https://user-images.githubusercontent.com/31414969/136691636-9b2bcfd0-c2f9-4424-b6b9-696757351ebd.png)

Level: X by TriAxis (https://gdbrowser.com/17235008)
Browser: Chrome 94.0.4606.71

**Comment by GDColon** [comment]
Aware of this, more or less intentional it doesn't really bother me
