### ISSUE TITLE
Move Robot + Spiders to the new icon code

### ISSUE THREAD

**Issue by GDColon** [GDColon/GDBrowser#188]
Currently, robots and spiders are generated in icon_old.js since I had way too much trouble getting them to work with the new and rewritten code. After many mental breakdowns I eventually said fuck it and gave up entirely.

💰 **I will pay $50 USD to whoever can successfully and correctly get spiders and robots working with the new code.** Because dammit, it's not gonna be me that's for sure. So screw it, I shall commit bounty

I am not responsbile for any mental or emotional damage caused to whoever attempts this

**Comment by jbmagination** [comment]
> I am not **responsbile** for any mental or emotional damage caused to whoever attempts this
responsible*

Challenge accepted

**Comment by masckmaster2007** [comment]
> EMOTIONAL DAMAGE
steven he

**Comment by GDColon** [comment]
I DID IT

**Comment by jbmagination** [comment]
NICE
