### ISSUE TITLE
Level downloading is blocked on local as well

### ISSUE THREAD

**Issue by PeacefulPotato** [GDColon/GDBrowser#191]
Hi, I just want to point out that now level downloading doesn't work when installing locally as well as from the main website [gdbrowser.com](https://gdbrowser.com). Can you please change the warning text so it doesn't say that these features still work locally when they don't anymore? Thanks!

**Comment by GDColon** [comment]
Shouldn't happen. Will leave this open and investigate properly in the future

**Comment by GDColon** [comment]
Downloading works fine on my end
