### ISSUE TITLE
Some sprite offsets are broken in new icon code

### ISSUE THREAD

**Issue by qimiko** [GDColon/GDBrowser#192]
Creating an issue just in case others might know what's up.

The broken offsets are most noticeable on cube 104, but I suspect that this is also causing issues with spider and robot icons (like spider 1's leftmost leg glow).

![image](https://user-images.githubusercontent.com/25387744/144970224-57cc7978-9e1e-45b4-8ff0-8a43917e7831.png)

![image](https://user-images.githubusercontent.com/25387744/144970191-63ec1f76-0258-4ced-91ea-a193d0d911ad.png)

Unsure what the root cause is, so far I've tried the following:
* accounting for the offset in the total sprite size (before getting the half position)
* setting the gravity for each layer
* ensuring offsets line up with what Geometry Dash says they are (they do)

For what it's worth, the y-position offsets seem to work perfectly fine.

**Comment by GDColon** [comment]
Cube 104 fixed, spider and robot I'm not sure (I gave up on them for a reason)
