### ISSUE TITLE
Improve Documentation

### ISSUE THREAD

**Issue by 101arrowz** [GDColon/GDBrowser#2]
The server side code is mostly undocumented and are therefore hard to read. As an example, the `LOADMODULES.js` file, as far as i can tell, recursively goes through the `/api` directory and requires each file in it. Because of odd coding practices (like using a ternary when we could just use logical OR) it took me a while to figure out.

PS: I'm not trying to diss your skills, hope I didn't come off too rude!

**Comment by GDColon** [comment]
LOADMODULES was actually shown to me by a friend when I first started coding. As much as I hate it, I don't really know a better way to run other files. I'm going to work on documenting + commenting code tomorrow, so hold tight ;)

**Comment by 101arrowz** [comment]
The more standard way of running the other files is to directly require them. For example:

```js
const analyze = require('./api/analyze.js');
```

Then you can simply `analyze(param1, param2, ...)`

**Comment by GDColon** [comment]
That'd be fantastic!

(Suddenly, I'm really happy to have joined GitHub)

**Comment by 101arrowz** [comment]
I've made the PR at #3.
