### ISSUE TITLE
Add download comments.

### ISSUE THREAD

**Issue by masckmaster2007** [GDColon/GDBrowser#206]
Download comments in a stylish way like:

![image](https://user-images.githubusercontent.com/63162857/161742499-8a4fc5ef-bb6c-48cc-9215-d88b7497e6ee.png)

Doing this manually bruh. If you're asking why am i archiving this account, it is just for fun.
The Archival account that i am cloning MANUALLY : NotClubette

**Comment by GDColon** [comment]
This is what the API is for

**Comment by masckmaster2007** [comment]
thx
