### ISSUE TITLE
New icons idea

### ISSUE THREAD

**Issue by Brendan18729** [GDColon/GDBrowser#208]
You should add robtop’s icons shown in the sneak peek to the online level kit. You should add his cube, swingcopter, spider, ball, and robot please. I know the first 3 are not currently in the game but I’m not sure about the ball or robot.

**Comment by GDColon** [comment]
When the icons are officially released they will be added. I rip all icons from the game files.

**Comment by Brendan18729** [comment]
Maybe you can find a png of them online?

**Comment by GDColon** [comment]
They're not PNGs. They're split into multiple layers and contain data on how to put them together.
