### ISSUE TITLE
password bug

### ISSUE THREAD

**Issue by RedStoneMatt** [GDColon/GDBrowser#21]
if you go on a level information to see its password and if the password of the level starts with a 0, the 0 won't be shown.
i think it's because you saved the passwords as an integer and so the code says that for example if the password is 0688 that it equals to 688 so it'll show 688 instead of 0688
to fix it you have to save the passwords as a string instead of an integer.
have a nice day

**Comment by GDColon** [comment]
Yeah, you're right. I'll fix that one ASAP!

**Comment by 101arrowz** [comment]
As far as I know (I tested just now) leading zeros are not noted by GD servers anyway. So if the password the creator inputs is "0688", "688" would work, except for the fact that three-number passcodes are blocked by GD clients. To avoid confusion, the best solution would be to ensure that the passcode is 6 digits long.
