### ISSUE TITLE
"Error: The specified procedure could not be found."

### ISSUE THREAD

**Issue by Noob1fy** [GDColon/GDBrowser#211]
ive switched so many versions
tried so many things

the closest I got was an error stating:
"Error: The specified procedure could not be found."

colon thinks its an issue on my end
but ive installed so many different node.js versions

![image](https://user-images.githubusercontent.com/92961327/163313723-1417c59d-2f2f-485a-b75c-fcba00927313.png)

**Comment by GDColon** [comment]
it's an issue on your end. google your problems, there is nothing wrong with the repo

**Comment by Noob1fy** [comment]
ik theres nothing wrong
i have googled

**Comment by Noob1fy** [comment]
i think my pcs just shit

**Comment by Noob1fy** [comment]
ill just fix it tomorrow
its 12:32

**Comment by jbmagination** [comment]
@GDasdf if this is still an issue, could you running this on your machine and letting me know what it says?
```node
const { dlopen } = require('process');
dlopen()
```

if this works as expected, you'll see `TypeError: process.dlopen needs at least 2 arguments` in the console

**Comment by GDasdf** [comment]
i fixed it, i committed to the repo like a week ago fixing it.
Canvas version was broken
