### ISSUE TITLE
Can't view list demons for some reason

### ISSUE THREAD

**Issue by Megarion** [GDColon/GDBrowser#213]
it just responds with this
![image](https://user-images.githubusercontent.com/82823698/163657990-060893da-700c-417b-b97a-97cd1a10349f.png)

**Comment by Noob1fy** [comment]
https://gdbrowser.com/search/*?type=demonlist

**Comment by Noob1fy** [comment]
that the link your trying?

**Comment by Megarion** [comment]
no it doesnt work when i view any list demon

**Comment by Noob1fy** [comment]
try running it locally

**Comment by GDColon** [comment]
Works for me
