### ISSUE TITLE
so the api is broken

### ISSUE THREAD

**Issue by masckmaster2007** [GDColon/GDBrowser#214]
i did a normal HTTP request and
```
HTTP/1.1 400 Bad Request
Server: nginx/1.14.0 (Ubuntu)
blah blah blah

You have been banned from commenting for 35 days. Reason: trolling on an alt (amogusdrip)

```
I don't have any link with that account, **NOR AM I BANNED**
so what happened ? pretty sure it's a duplicate issue

**Comment by masckmaster2007** [comment]
i love trying to break stuff on GD

**Comment by sudocode1** [comment]
to my knowledge the website ip is blocked because of someone comment spamming via it, so now no one can comment via the website, someone correct me if im wrong

**Comment by GDColon** [comment]
Works fine locally so not a repo issue
