### ISSUE TITLE
Servers died

### ISSUE THREAD

**Issue by TechStudent11** [GDColon/GDBrowser#217]
![image](https://user-images.githubusercontent.com/76978184/166563173-31cba501-3a31-485e-a643-12f5b4c0a18d.png)

**Comment by GDColon** [comment]
Aware, been pulling my hair out over this for the past hour. Might be a ddos or something

**Comment by TechStudent11** [comment]
I don't know, maybe you should keep the issue open 'til it's resolved. Just so that you get any more of these issues.

**Comment by TechStudent11** [comment]
Oh wait it's back for me 

![image](https://user-images.githubusercontent.com/76978184/166564819-88a14645-7711-40e3-93b7-6d191a0d28c6.png)
