### ISSUE TITLE
Profile Comment API just returns [ ]

### ISSUE THREAD

**Issue by Proyo9** [GDColon/GDBrowser#218]
I'm making a "GD Biography" website where it generates a biography for Geometry Dash players and I would like to add a 'quotes' section where it lists profile comments but the API is just returning [ ]

**Comment by TheTechRobo** [comment]
How are you using the API? What's the endpoint and payload you're using?

**Comment by Proyo9** [comment]
Not exactly sure what any of that means but if you just look at the example link that's supposed to show Serponge's profile comments it just shows [ ] instead of the proper data https://gdbrowser.com/api/comments/4170784?type=profile

**Comment by TheTechRobo** [comment]
Oh, yeah, I can confirm.

**Comment by GDColon** [comment]
Use account ID, not player ID
