### ISSUE TITLE
I want to delete a comment but my iPhone 6 died

### ISSUE THREAD

**Issue by masckmaster2007** [GDColon/GDBrowser#219]
So I was smart enough to make a comment that I regretted. I want to remove it on GDBrowser but nor the API nor the GUI lets me...

**AAAAAAAAAAAAAAAAAAAAAAAAAAA**

**Comment by TheTechRobo** [comment]
You could try GD's official API. It's much more complicated, though, and I wouldn't recommend beginners doing it.

https://docs.gdprogra.me/#/endpoints/deleteGJComment20 for level comments and https://docs.gdprogra.me/#/endpoints/deleteGJAccComment20 for account comments.
