### ISSUE TITLE
How do I comment?

### ISSUE THREAD

**Issue by TechStudent11** [GDColon/GDBrowser#225]
When looking around in the comment interface, there is no place for me to add a comment.

![image](https://user-images.githubusercontent.com/76978184/168495315-e9169904-2d3e-495c-b7e8-b4cdb0999fdd.png)

How do I comment on levels through GD Browser?

**Comment by GDColon** [comment]
You can't anymore, RobTop blocked it. Hoping to bring it back in 2.2

**Comment by TechStudent11** [comment]
> RobTop blocked it

Aw man :(. Why does Rob have to block so many things? I can kind of understand him from a moral standpoint, but it's not hurting GD in anyway, shape or form.

**Comment by TechStudent11** [comment]
The API for posting a comment is still up right?

**Comment by GDColon** [comment]
It doesn't work unless you're on localhost

**Comment by TechStudent11** [comment]
> It doesn't work unless you're on localhost

How does that work? It's still sending the requests to the Boomlings server, is not?

**Comment by TechStudent11** [comment]
Also, suggestion: add a list of features RobTop has blocked. It'll help with issues like this.

**Comment by GDColon** [comment]
RobTop blocked my server's IP, so locally is fine. Please stop commenting here my emails are getting spammed
