### ISSUE TITLE
Texture pack support for the Icon Kit

### ISSUE THREAD

**Issue by fancythedeveloper** [GDColon/GDBrowser#230]
This is definitely more of an enhancement/feature request rather than an issue, but since this repository doesn't have Discussions enabled, I guess I'll just put it here.

Anyways, since the icon kit is now offline. I suppose texture pack support wouldn't be out of the question now, since the files of the texture pack doesn't need to be stored on the server anymore (I think).

**Comment by GDColon** [comment]
2.2 is redoing how icons are stored, I'll add it then
