### ISSUE TITLE
Don't you dare removing the api

### ISSUE THREAD

**Issue by masckmaster2007** [GDColon/GDBrowser#235]
Please don't remove it ! Your API is much simpler than GDDocs !
I DON'T EVEN KNOW HOW TO ENCRYPT A PASSWORD TO GJP
i use that as a base for my GD projects !
Please don't remove it or give me at least some mirrors of existing GDBrowsers !

**Comment by GDColon** [comment]
your tears are delicious

**Comment by masckmaster2007** [comment]
Atleast give me a mirror of the current site or give me instructions ON SETTING IT UP ONLINE

**Comment by masckmaster2007** [comment]
very serious dev indeed
