### ISSUE TITLE
OK so how do i run it on heroku ?

### ISSUE THREAD

**Issue by masckmaster2007** [GDColon/GDBrowser#236]
I did everything possible to run it.
After some time i did it
URL is http://dgdps.herokuapp.com/
now it redirects me to their site instead of gdbrowser, WOHOOOOOOOOOOO

**Comment by masckmaster2007** [comment]
do i have to contact heroku somehow ?

**Comment by masckmaster2007** [comment]
or when do forms open again ?
useless question because my gdps will get instant rejeced

**Comment by masckmaster2007** [comment]
![image](https://user-images.githubusercontent.com/63162857/173249219-8ccae77f-d225-4205-b219-b84ec39ddce5.png)

**Comment by masckmaster2007** [comment]
oh mais ferme ta bouche

**Comment by masckmaster2007** [comment]
tell me what to do instead of closing

**Comment by GDColon** [comment]
stop bothering me

**Comment by masckmaster2007** [comment]
ok, but what can i do ?

**Comment by masckmaster2007** [comment]
![image](https://user-images.githubusercontent.com/63162857/173279870-7a4694e2-8496-4e0c-a9b1-179b2c12d99f.png)
you got a point because i could at least run it locally
