### ISSUE TITLE
add support for subdomains

### ISSUE THREAD

**Issue by masckmaster2007** [GDColon/GDBrowser#237]
GDBrowser needs to have a top-level domain, but i am using heroku because it's the only tool that works and i only have a subdomain
how do i do that ?

Please don't close that i really try to make your "messy" code work

**Comment by Nadwey** [comment]
You can do that by removing last subdomains from request in `index.js`.

Few demos:
| Website                       | Code                                                                                                 | Demo                                                                      | Notes                                                                                                                                                   |
| ----------------------------- | ---------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------- |
| [Heroku](https://heroku.com/) | [#hosting-websites-fix-heroku](https://github.com/Nadwey/GDBrowser/tree/hosting-websites-fix-heroku) | [gdbrowser-heroku.herokuapp.com](https://gdbrowser-heroku.herokuapp.com/) | You need to remove **1** last subdomain from request. Also, heroku gives you environment variable _PORT_ and you need to host your server at that port. |
| [Replit](https://replit.com/) | [#hosting-websites-fix](https://github.com/Nadwey/GDBrowser/tree/hosting-websites-fix)               | [gdbrowser.nadwey.repl.co](https://gdbrowser.nadwey.repl.co/)             | You need to remove **2** last subdomains from request.                                                                                                  |
| [Glitch](https://glitch.com/) | [#hosting-websites-fix](https://github.com/Nadwey/GDBrowser/tree/hosting-websites-fix) should work   | -                                                                         | **Didn't work**, ran out of space lol.                                                                                                                  |

**Comment by masckmaster2007** [comment]
Thanks, I'm gonna check that out !
I'm gonna close it once done :D

**Comment by masckmaster2007** [comment]
@Nadwey 
![image](https://user-images.githubusercontent.com/63162857/175923039-8e72b60a-9794-4be6-b6d0-508f8247244c.png)
So ngrok works. I'm gonna try on replit too. Thank you for the help !

**Comment by masckmaster2007** [comment]
Closed: https://GDBrowser.jeanappser.repl.co works !

**Comment by Nadwey** [comment]
Btw heroku demo just broke I don't know why.

**Comment by masckmaster2007** [comment]
well replit works 
![image](https://user-images.githubusercontent.com/63162857/175933506-088ec1d0-4b3b-49d4-bee2-ee105e019019.png)
and i am going to use custom domains
yes i want to go next gen
