### ISSUE TITLE
Error: Cannot find module 'express'

### ISSUE THREAD

**Issue by 3030years** [GDColon/GDBrowser#259]
Require stack:
- C:\Users\N\Downloads\GDBrowser-master\GDBrowser-master\index.js
←[90m    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)←[39m
←[90m    at Function.Module._load (node:internal/modules/cjs/loader:778:27)←[39m
←[90m    at Module.require (node:internal/modules/cjs/loader:1005:19)←[39m
←[90m    at require (node:internal/modules/cjs/helpers:102:18)←[39m
    at Object.<anonymous> (C:\Users\N\Downloads\GDBrowser-master\GDBrowser-master\index.js:1:17)
←[90m    at Module._compile (node:internal/modules/cjs/loader:1105:14)←[39m
←[90m    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)←[39m
←[90m    at Module.load (node:internal/modules/cjs/loader:981:32)←[39m
←[90m    at Function.Module._load (node:internal/modules/cjs/loader:822:12)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)←[39m {
  code: ←[32m'MODULE_NOT_FOUND'←[39m,
  requireStack: [
    ←[32m'C:\\Users\\N\\Downloads\\GDBrowser-master\\GDBrowser-master\\index.js'←[39m
  ]
}

**Comment by 3030years** [comment]
I have no idea why this is

**Comment by 3030years** [comment]
can someone help me?

**Comment by Nadwey** [comment]
Did you run `npm install` before starting the page?

**Comment by 3030years** [comment]
I had to reinstall chocolaty!
