### ISSUE TITLE
[FEATURE REQUEST] Full-fledged level editor/viewer

### ISSUE THREAD

**Issue by 101arrowz** [GDColon/GDBrowser#26]
This is a far-future idea, but at some point levels can be edited (or at least viewed, which would be a lot easier I'd think) in the browser and offer the option to download it to a user's computer. Heck, with a physics engine you could even play it!

We can [abuse others' hard work](https://github.com/gd-edit/GDAPI/blob/master/GDAPI/GDAPI/Objects/GeometryDash/General/Level.cs) to determine what is what in the encrypted data. I have no C# experience (only some Java) but I can probably try to <strike>steal it all</strike> port their code over to Node.js.

Let me know if this is an idea for the future or if it isn't a goal for GDBrowser.

(By the way, that code is one part of the parsing step - UI is a whole different animal. If this is an idea, it definitely won't be possible without at least three or four weeks of work by multiple people. Also, I know `analyze.js` already exists, but this is an extension of it. Maybe you've already seen the GDE project and used it for `analyze.js` but again this is an idea.)

**Comment by Qufyy** [comment]
Although it may be very hard to do, I can help with the C# part.

**Comment by GDColon** [comment]
I highly doubt that this will ever happen. But who knows.
Anyways I'm gonna close the issue because I don't like seeing the number higher than it should be, but I guess now is an ideal time to try GitHub's 'projects' feature

**Comment by jbmagination** [comment]
This would be sweet, however seems far-fetched. GDEdit is Windows-only, how do you even expect to run this in a browser without some SERIOUS lag?
