### ISSUE TITLE
Message decryption

### ISSUE THREAD

**Issue by MegaSa1nt** [GDColon/GDBrowser#260]
Hi everyone! Does anyone know how gd converts body from message to readable text?

![image](https://user-images.githubusercontent.com/49565695/184405928-18b4cc1b-3d24-4da5-8b51-3a5e384a9109.png)

Both body and subject is 'test', both body and subject are utf8 in database, but subject easily decodes as it is base64
How can i decode message body? I tried checking getMessages.js but i didnt understand anything

**Comment by fancythedeveloper** [comment]
https://docs.gdprogra.me/#/resources/server/message

**Comment by MegaSa1nt** [comment]
> https://docs.gdprogra.me/#/resources/server/message

Thank you!
