### ISSUE TITLE
Use flexbox instead of hardcoded values

### ISSUE THREAD

**Issue by 101arrowz** [GDColon/GDBrowser#28]
I'm starting to feel that I'm making so many issues and PRs that I'm being annoying, so please let me know if that's the case and I'll take the pace down a notch haha.

[Flexbox](https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Flexbox) is a CSS layout format that allows content to resize based on the amount of space it's allotted and removes the need to hardcode values such as `padding-right: 11%` to make three items in a `<div>` symmetrical. Instead, we use flexbox with `justify-content: space-between` and simply put the three items in. The browser puts space between the elements for us, automatically and evenly. There's other benefits such as `align-items: center` to automatically align things vertically. It's really cool, and I suggest you take a look even if you decide it isn't the right call for GDBrowser.

I'm only making this issue because there are many places when seemingly random values are coded in where flexbox would serve much better.

Thanks for reading!

**Comment by GDColon** [comment]
.

..

what

**Comment by 101arrowz** [comment]
Basically, here are the Four Noble Truths of Flexboxism:
1. Suffering exists
2. The cause for suffering is that testing hardcoded values until it looks nice/symmetrical is painful, and the values don't work across all browsers
3. There is an end to suffering
4. The end to suffering is to wrap elements in flexbox containers and use theproperties

**Comment by GDColon** [comment]
I'm gonna need an example for this one chief. You can make a PR or just explain through a beautiful diagram.

**Comment by 101arrowz** [comment]
I've been working on using Flexbox for the layout, should be done by today or early tomorrow :)

**Comment by 101arrowz** [comment]
It's done.
