### ISSUE TITLE
Objects showing up way too big in analysis

### ISSUE THREAD

**Issue by siky112** [GDColon/GDBrowser#31]
The title says it all. This can fix itself sometimes, but it's still weird.
Attached are images of this happening:
![gdbrowserbug](https://user-images.githubusercontent.com/20342336/68491306-7043c800-01ff-11ea-9cba-1a31ba4157b2.PNG)
![gdbrowserbug2](https://user-images.githubusercontent.com/20342336/68491308-7174f500-01ff-11ea-963d-b91a75246dba.PNG)
![gdbrowserbug3](https://user-images.githubusercontent.com/20342336/68491313-72a62200-01ff-11ea-9d46-7f1d86bfbf62.PNG)
![gdbrowserbug4](https://user-images.githubusercontent.com/20342336/68491315-746fe580-01ff-11ea-8c6c-a556f91546b2.PNG)

**Comment by siky112** [comment]
Another image, if that's of any use to you:
![gdbrowserbug5](https://user-images.githubusercontent.com/20342336/68492349-24dde980-0200-11ea-9f8b-4d246eda46b1.PNG)

**Comment by GDColon** [comment]
Strange... what device are you on?

**Comment by siky112** [comment]
PC.

**Comment by GDColon** [comment]
Just tried on Edge and you're right. That's definitely an issue. I do all my testing on Chrome (like a casual) so maybe it's reading the HTML differently or something.

**Comment by GDColon** [comment]
Update: Interesting thing I found - the issue fixes by resizing your window. Very strange...

**Comment by siky112** [comment]
Huh, maybe it's something with the way Edge handles window sizes?

**Comment by siky112** [comment]
Also, resizing isn't foolproof, I tried resizing and this happened:
![gdbrowserbug6](https://user-images.githubusercontent.com/20342336/68493968-61aae000-0202-11ea-99d6-604413618074.PNG)

**Comment by 101arrowz** [comment]
This might be an Edge bug, but the solution is to explicitly set the height to, say, `80%` for the images.
