### ISSUE TITLE
Custom songs with tildes are parsed incorrectly

### ISSUE THREAD

**Issue by GDColon** [GDColon/GDBrowser#34]
todo: uhh.. fix this one

![image](https://user-images.githubusercontent.com/56617416/68533029-76ff3780-02f2-11ea-8474-10f361ef7dfa.png)

**Comment by 101arrowz** [comment]
Who in their right mind would put a tilde in their song name? They're simply out to get us poor developers, make us need to handle more edge (ha get it cuz Edge bad) cases.

Seriously though, we dont process song names. How could this happen? Maybe the XSS-prevention regex?

**Comment by GDColon** [comment]
When boomlings.com sends the response for the song name, it seperates the different key/values with tildes. Groan...

**Comment by 101arrowz** [comment]
Why can't RobTop just be a good developer, jesus christ

He could literally hire some 9-year-old nerd who knows PHP who would give him a better backend. Why would we want separate keys for a SINGLE STRING?!?!??!

Rant aside, do you want me to fix it? It looks like you know how to do it better, so I'd prefer if you gave it a shot.

**Comment by GDColon** [comment]
I can do it, don't worry. It works fine when you download the level (download.js) but otherwise it's broken.

**Comment by SeeBeyondDev** [comment]
Maybe count the number of tildes in the string, which should be the same, and if it's more then needed, then that means there's a tilde in the song name, so then we truncate all text that comes before and after the song name and then we can display what's left

**Comment by GDColon** [comment]
Alright, it's been fixed. It was actually because of the colon in the song name - they're the main 'splitter' of the response.
