### ISSUE TITLE
some sort of visual bug

### ISSUE THREAD

**Issue by GDColon** [GDColon/GDBrowser#37]
I've gotten about three or four bug reports with something along the lines of this:
(glitchy auto faces)

Any of y'all have any ideas on what's causing it?
Screenshot is freshly harvested from a Discord DM.

![image](https://user-images.githubusercontent.com/56617416/68538807-4cd86480-0348-11ea-865c-eb459702b93f.png)

**Comment by 101arrowz** [comment]
It could be an inconsistency with the `display: inline-block` across browsers, but I'm not sure. I might be able to try to reproduce this (hopefully) and find the issue, but no promises.<sup><strike>if we had used flexbox I don't think this would happen but ok</strike></sup>
