### ISSUE TITLE
Analysis of Old Levels with Colors

### ISSUE THREAD

**Issue by zmxhawrhbg** [GDColon/GDBrowser#43]
I'll be honest here: I was planning on doing this myself (and had - at the expense of 2.0 color support).
The header colors are parsed the exact same way minus some things:
Opacity is always 1, there are no copied colors, and they're not in the kS38 header but split into many more header values.
One thing is that I have no idea how it _should_ be integrated into the API, you could either do it the 1.9 way and send it as part of the settings, which would require anything using the API to deal with it or parse it into the 2.1 format, which would require the API itself to deal with it.

**Comment by GDColon** [comment]
Yeah, the big issue is that there's no kS38 header. But I might try to find a workaround.
