### ISSUE TITLE
Cannot find module "SecretStuff.json"

### ISSUE THREAD

**Issue by WZ2100ModsFan** [GDColon/GDBrowser#45]
npm install: `npm notice created a lockfile as package-lock.json. You should commit this file.
added 267 packages from 215 contributors and audited 539 packages in 241.841s
found 0 vulnerabilities`
node index.js `Error: Cannot find module './misc/secretStuff.json'`
Did i miss anything? I thought this file already existed after i ran npm install.

**Comment by zmxhawrhbg** [comment]
https://github.com/GDColon/GDBrowser/blob/357a72eaded8ac45ab2e1c1d126391f547dc723f/index.js#L23-L26

just make a file in `./misc/` called `secretStuff.json` and give it the contents
```{"id": 1, "gjp": "aee"}```
it might crash in level leaderboard loading, be warned

**Comment by WZ2100ModsFan** [comment]
Resolved for now.
