### ISSUE TITLE
[Bug] Clicking a name with a space in it redirects to everything before the space

### ISSUE THREAD

**Issue by jbmagination** [GDColon/GDBrowser#48]
For example, if we go to [level ID 1](https://gdbrowser.com/comments/1), we'll see a user called "Melting Ice" somewhere in that comments list. If you click on "Melting Ice", you'll be redirected to "Melting".

**Comment by GDColon** [comment]
Easy fix. I'll get to it ASAP.

**Comment by GDColon** [comment]
Fixed.
