### ISSUE TITLE
[Feature Request] Import save data for level progress (and potentially the icon kit?)

### ISSUE THREAD

**Issue by jbmagination** [GDColon/GDBrowser#49]
When saving data to the cloud, it also saves the progress you have on levels, both normal and practice. It also saves attempts, I believe.

It would be pretty cool to be able to load your account data to save your progress, and potentially even be able to use it to comment on GDBrowser.

The icon kit might also be nice to add for this feature as well.

**Comment by GDColon** [comment]
This is way too crazy of a feature to add, and even if it's doable - I'm not going that far. Sorry :v
