### ISSUE TITLE
[Feature Request] A rewrite.

### ISSUE THREAD

**Issue by kaguyaln** [GDColon/GDBrowser#50]
I as a primary JavaScript developer am willing to help out with an overall code rewrite, or to maintain one if allowed by you. I understand if you wish not to by virtue of the code working; but I ask if I may help out with such on the basis of improvement and to make it easier on future contributors to help out with the codebase, such as myself; to improve and build upon what is provided here.

I primarily say this not out of spite or disgust with the current codebase, but as a helping figure.

**Comment by GDColon** [comment]
Really interesting offer, really happy you're open to do this!
Cleaner code is always really nice, but at the same time, it's always easier to understand your own code.
Can you give an example of how you would rewrite the code? Perhaps send a PR changing just one of the existing files and we can work from there.
