### ISSUE TITLE
Daily enhancements

### ISSUE THREAD

**Issue by jbmagination** [GDColon/GDBrowser#53]
I’ve noticed that daily was unchanged for a while. If this ever happens again, it breaks the daily page. Is there a way to fix this, for example GDProfiles’ daily page? After all, there is a node.js package for accessing the API [here](https://www.npmjs.com/package/gdprofiles), but I have no idea how limited it is for dailies and weeklies.

edit: ok i was kinda harsh to robtop ngl

**Comment by GDColon** [comment]
Redirecting back to the homepage is intentional
