### ISSUE TITLE
Cannot search for levels with song Stay Inside Me

### ISSUE THREAD

**Issue by muzikbike** [GDColon/GDBrowser#54]
There are levels such as 35032968 which are hacked to have practice mode music set as the level's actual theme, but searching with Stay Inside Me set to the song name doesn't work, and there's not enough room to fit "Practice: " before it either.

**Comment by jbmagination** [comment]
Okay, I just played the level and what in the world?!

Also, if it’s just a character limit that could be fixed.

**Comment by muzikbike** [comment]
Browser does display it without the Practice:  though.

**Comment by GDColon** [comment]
This is an issue with the GD servers, it's unable to search for levels with that song.
