### ISSUE TITLE
Display trail and death effect on GD user profiles

### ISSUE THREAD

**Issue by muzikbike** [GDColon/GDBrowser#56]
I'm not sure if these get sent at all with the other icon data, but if they do it could be pretty handy to have them be displayed along the rest of the selected icon data. Also, maybe display the swing gamemode along the icons as well, so people know what it'll look like come 2.2?

Would also be handy to display default mini icon settings, dash fire colour settings, spider teleport effect settings and wave trail colour settings in the profile as well but I doubt those get sent over the server at all.

**Comment by muzikbike** [comment]
Another idea: a button somewhere that inverts the colours of the selected icons so their variations in dual mode can be seen

**Comment by Altenhh** [comment]
you can create a separate issue for your other idea.

**Comment by GDColon** [comment]
death effect: sure

**Comment by GDColon** [comment]
death effect: sure
swingcopter: no
inverted colors: no
mini, dash fire, spider color, etc: this is client side and does not appear on the servers

**Comment by GDColon** [comment]
Done

**Comment by muzikbike** [comment]
I assume trail info doesn't get sent then?

**Comment by GDColon** [comment]
I believe so
