### ISSUE TITLE
GDBrowser sends bugged status messages to GD

### ISSUE THREAD

**Issue by jbmagination** [GDColon/GDBrowser#58]
When sending a status to GDBrowser, it looks fine on the site:
![](https://i.imgur.com/nSGWgAa.png)

But on Geometry Dash, it looks... well, different:
![](https://i.imgur.com/OxiTLdG.png)

For comparisons sake, here’s a normal status:
![](https://i.imgur.com/FQsF11a.png)

Which works as expected on GDBrowser:
![](https://i.imgur.com/XLCuHCq.png)

**Comment by GDColon** [comment]
Been looking into this one, trying to find the cause
