### ISSUE TITLE
Level analysis: Ability to display a full list of counts of each unique object

### ISSUE THREAD

**Issue by muzikbike** [GDColon/GDBrowser#59]
Currently the level analysis only displays specific object counts for triggers, rings, and groups the remaining objects into categories. I think there should be a more specific and in-depth analysis option as well, which lists all unique object types in order of their internal numeric ID.

Objects which cannot normally be accessed through the editor (e.g. old colour triggers, deprecated clubstep blocks) could have a separate font colour.

28651344 could be used to test this feature.

**Comment by GDColon** [comment]
This seems a little excessive
