### ISSUE TITLE
Alternative way to fill in names for default songs

### ISSUE THREAD

**Issue by muzikbike** [GDColon/GDBrowser#60]
Since it takes time to type in the name of a song, maybe there could be a faster way to input song names? One thought would be to have a button which could be pressed, revealing a menu with the name of each song, and clicking on the name of such a song would automatically input it as text into the input text box. Would be quicker for the ones with longer names

**Comment by GDColon** [comment]
Honestly I was just being lazy so I added a text input. I might do this at some point.
