### ISSUE TITLE
Display full difficulty name below demon in search results

### ISSUE THREAD

**Issue by muzikbike** [GDColon/GDBrowser#61]
Currently it just displays demon, would probably be better if it displayed the whole difficulty name.
![F5E61F84-6393-4B8F-83C1-0F53E22CBF14](https://user-images.githubusercontent.com/52297970/71316068-ea53a780-2461-11ea-9178-43bbea4912e3.jpeg)

**Comment by Altenhh** [comment]
the face already describes pretty well on what difficulty it is, so i dont think we need to extend the name
