### ISSUE TITLE
Clicking on icons in user profiles should display info on the selected icon

### ISSUE THREAD

**Issue by muzikbike** [GDColon/GDBrowser#62]
- Internal numerical ID of icon
- Associated achievement
- Color 1 ID
- Color 2 ID

**Comment by GDColon** [comment]
Hovering over the icon already gives basic info, but I'm not going any further than that.

Also please, chill out with all the issues. It's more convenient to just tell me your ideas on Discord. Catch me at discord.gg/juniverse
