### ISSUE TITLE
Section for jump pads in level analysis

### ISSUE THREAD

**Issue by muzikbike** [GDColon/GDBrowser#63]
It seems odd that jump rings are dedicated a section, but jump pads aren't.

**Comment by muzikbike** [comment]
Order should be magenta, yellow, red, cyan

Also, reorganise the jump rings section so that they're also somewhat sorted by jump height: black, magenta, yellow, red, cyan, green, green dash, magenta dash, custom

**Comment by GDColon** [comment]
- Orbs are ordered from most to least (in that level)
- Jump pads... maybe. They just look a little weird as an image.

Please use Discord/Twitter for suggestions, GitHub issues gets awfully flooded.
