### ISSUE TITLE
Object #34 appears upside down in level analysis

### ISSUE THREAD

**Issue by muzikbike** [GDColon/GDBrowser#64]
![E4692E51-8226-4744-952E-4C210E820DD1](https://user-images.githubusercontent.com/52297970/71390974-3d606280-25fa-11ea-9d50-6184a698582f.png)
Test case: 28651344

**Comment by Altenhh** [comment]
i dont think thats an actual Start Position trigger. iirc i saw something like that in 2.2. so its intentional

**Comment by GDColon** [comment]
Intentionaly, it's the 'fake start pos' object.
