### ISSUE TITLE
Response timeout returns a really gross error to the client

### ISSUE THREAD

**Issue by GDColon** [GDColon/GDBrowser#65]
Seriously, does anyone know how to change this

**Comment by LionblazeYT** [comment]
we need a little more info to troubleshoot the error colon.  what's the error?  a good issue troubleshoot request will give info on where and how the error is happening, and what it looks like.  could you do so?

**Comment by AwesomeArsh** [comment]
Every time I try to log in, It keeps saying error but doesn't give me a reason or any details.

**Comment by GDColon** [comment]
eh forget it
