### ISSUE TITLE
Spaces don't work on Safari and I can't post comments.

### ISSUE THREAD

**Issue by quriguess** [GDColon/GDBrowser#72]
Exactly what the title says.

**Comment by GDColon** [comment]
Can I have some more details please?

**Comment by 101arrowz** [comment]
What version of Safari? Older versions don't support one of the necessary features (`fetch()`)

**Comment by quriguess** [comment]
> Can I have some more details please?

Whenever I type a space it gets deleted. It does, however, allow me to use spaces if I abuse autocorrect (which is kind of a pain.)

> What version of Safari? Older versions don't support one of the necessary features (`fetch()`)

I am not entirely sure. It's a pretty old computer I'm on (MacBook Pro 2013)
I'll try updating Safari. It has been telling me that updates are available for a while but I don't know what for.

**Comment by 101arrowz** [comment]
Yep, that's a Safari issue. Update or use Chrome if you want to use all of GDBrowser.

**Comment by quriguess** [comment]
Safari is on version 13.0.5.

**Comment by quriguess** [comment]
Another thing, I downloaded Chrome to test comments (and spaces) and the spaces do work, but it still doesn't let me make comments. This might be completely stupid, but is it possible it might be that the servers don't accept 150 character limit comments anymore? I don't know much about servers or programming at all, just a thought I had.
