### ISSUE TITLE
I want to load "/api/profile/id" data through 'accountID'.

### ISSUE THREAD

**Issue by RedLime** [GDColon/GDBrowser#73]
Currently in id "/api/profile/id" api, id only works with playerID. Can I load this with accountID? I looked at the api documentation, but I could not find it. As expected, I think it's not woking yet on GDBrowser, or only accountID cannot be loaded from GD's load data php.
Is there any way to add this function or load playerID by accountID only?

**Comment by GDColon** [comment]
Yeah, I plan on adding it. It's just a little annoying because of how the profile API is coded. It searches by player name/id, then gets the account of the first result. Because of async and promises and stuff, you can't just... skip a step. But I'll try to find a workaround.

**Comment by RedLime** [comment]
> Yeah, I plan on adding it. It's just a little annoying because of how the profile API is coded. It searches by player name/id, then gets the account of the first result. Because of async and promises and stuff, you can't just... skip a step. But I'll try to find a workaround.

thanks for answer :D

**Comment by Flux3on** [comment]
I think AccountID data should be loaded through ```api/account/id``` instead of ```api/profile/id```.

**Comment by GDColon** [comment]
Added in latest commit!
