### ISSUE TITLE
"/api/profile/UserID" can't show info for unregistered users

### ISSUE THREAD

**Issue by Flux3on** [GDColon/GDBrowser#77]
If, for instance, I go to https://gdbrowser.com/api/profile/26 (UserID for Clatchet, one of the few unregistered users with their username untouched), cannot get anything returned except a -1

**Comment by GDColon** [comment]
I plan on fixing this

**Comment by GDColon** [comment]
Update: It's a problem with the GD servers unfortunately

**Comment by Flux3on** [comment]
F
