### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by WOSHIZHAZHA120** [GDColon/GDBrowser#81]
1: use getGJMapPacks21.php
getGJMap Packs21.php return like these:
1:1:2:Epic Pack:3:126,130,438:4:8:5:2:6:5:7:255,255,255:8:255,255,255#1:0:10#1f37ee82c87f40ad19c7746450629d5ca5893808
How to decode?
1:packID:2:packName:3:levels:4:Stars:5:coins:6:difficulty:7:title Color:8:colors2
If there have more one packs, then they will be separated by "|"
2:use getGJSongInfo.php
Because Private Server have custom songs (didn't find on NG)
decode: 1~|songID|2|songName|3|authorID(or something)|4|authorName|5|songSize|6||10|downloadLink|7||8|~0
I didn't know node.js so i cant help you :(
Hope it helps you :)

**Comment by WOSHIZHAZHA120** [comment]
4:"stars"

**Comment by WOSHIZHAZHA120** [comment]
2:use getGJSongInfo.php
Because Private Server have custom songs (didn't find on NG)

**Comment by WOSHIZHAZHA120** [comment]
How to decode the songInfo?
1~|~songID~|~2~|~songName~|~3~|~authorID(or 
something)~|~4~|~authorName~|~5~|~songSize~|~6~|~~|~10~|~downloadLink~|~7~|~~|~8~|~0

**Comment by WOSHIZHAZHA120** [comment]
1~|songID|2|songName|3|authorID(or something)|4|authorName|5|songSize|6||10|downloadLink|7||8|~0

**Comment by WOSHIZHAZHA120** [comment]
I didn't know node.js so i cant help you :(

**Comment by GDColon** [comment]
I already responded to these two concerns in #79 

- getGJMapPacks isn't needed since it never changes. Hardcoding it greatly speeds up the load time.
- getGJSongInfo also isn't needed since getGJLevels should already provide all the song information.

I understand your concern for compatability private servers, so it's possible that I might come up with a way to show custom map packs in the future.

**Comment by WOSHIZHAZHA120** [comment]
Is this a bug? It appears as follows in the game: 
![image](https://user-images.githubusercontent.com/52521836/75500328-90de9a80-5a07-11ea-9533-3ba1195ef5c3.png)
But in GDBrowser it shows as follows: 
![image](https://user-images.githubusercontent.com/52521836/75500413-d1d6af00-5a07-11ea-926b-5873fa2554a7.png)
Why songs always Stereo Madness
(Sorry for my bad English,so I use translate)
