### ISSUE TITLE
Mobile: Outer box formatting

### ISSUE THREAD

**Issue by ItzSwirlz** [GDColon/GDBrowser#82]
Don’t know if this is on Non-mobile too but the outline of the box to display the levels is well, nonexistent.

![E30F5A3A-585C-4193-BD32-FE8762B8050D](https://user-images.githubusercontent.com/24401303/76171373-d9612b00-6160-11ea-8ad8-7c8766a02b40.png)

**Comment by GDColon** [comment]
Your browser doesn't support box outlines.
