### ISSUE TITLE
[Suggestion] Icon Kit Colors

### ISSUE THREAD

**Issue by ItzSwirlz** [GDColon/GDBrowser#83]
I suggest you being able to literally, yes, pick a color and be able to more personalize your icon. I’m sure GD does this by taking an icon, then making color 1 and color 2 then telling the game to paint over it and copy instead of wasting disk space.

So let’s make it easy:

1) Debunk all above.
2) Add in a box to paste a Hex Code (I’m sure because of 6/8 or whatever bit there may have to be or will be a limit)
3) When done and published, try a Color Wheel like in the Editor.
4) If possible-maybe choose a certain number of colors-like 3 or a rainbow strip color, like ToshDeluxe. We can’t go on forever but adding an extra color would look sick IMO.

**Comment by GDColon** [comment]
It's a neat idea, but I don't think it's worth adding
