### ISSUE TITLE
Why Hall of Fame but not Featured?

### ISSUE THREAD

**Issue by ItzSwirlz** [GDColon/GDBrowser#84]
So you ditched Featured for Saved Levels. But why?, because it leaves hall of fame.

Hall of Fame counts as featured-but most of the time it’s honestly pretty buggy, laggy or overdecorated.

But the featured will show hall of fame but hall of fame DOES NOT show the ONLY FEATURED, only the HALL OF FAME.

Featured is same as hall of fame pretty much, so you minus well mix it into like one page or something. Why not.

**Comment by GDColon** [comment]
I might add it to the search page along with awarded in the future
