### ISSUE TITLE
[Firefox 74] Posting/voting on comments doesn't work

### ISSUE THREAD

**Issue by SweetEiche** [GDColon/GDBrowser#86]
Attempting to interact with comments displays an error message saying that the GD servers rejected your vote. Checking this request in the developer tools reveals a status code of 400, and the error seems to be somewhere in the remote address' HTTPS certificate? I wouldn't know, I'm not a web developer. The vote buttons (like.png/dislike.png) also don't show up for whatever reason.

**Comment by ItzSwirlz** [comment]
Did you check to make sure JavaScript and all other scripts and stuff are enabled? (Like on Brave)

**Comment by ItzSwirlz** [comment]
But actually yes-i'm having the same issue.

**Comment by SweetEiche** [comment]
Upon some testing, the issue seems to be related to my rather strict ad-blocking settings. Oops
