### ISSUE TITLE
you want to add the level preview function in GDBrowser?

### ISSUE THREAD

**Issue by WOSHIZHAZHA120** [GDColon/GDBrowser#88]
Like This: https://github.com/WOSHIZHAZHA120/Geometry-Dash-Level-Preview
but it's on PHP language and missing many texture

**Comment by WOSHIZHAZHA120** [comment]
Because my english is so bad...
So i used the google translate...

**Comment by ItzSwirlz** [comment]
1) (about the thing) I can't seem to run the app. How does it work? Things you should explain for things.

2) You should fork this repo, (GDBrowser) and then import the changes and maybe open a pull request.

**Comment by WOSHIZHAZHA120** [comment]
I'll try,thank you for tips @ItzSwirlz
