### ISSUE TITLE
Is this bug?

### ISSUE THREAD

**Issue by WOSHIZHAZHA120** [GDColon/GDBrowser#89]
When i used GDBrowser on GDPS, all demon is Extreme Demon and song always stereo madness.
![image](https://user-images.githubusercontent.com/52521836/77811285-5a627100-70d4-11ea-8584-9675f31607e1.png)
Like this, this level in game is Medium Demon but here is Extreme Demon and song in game is back on track but this is stereo madness

**Comment by 101arrowz** [comment]
Mind posting the source code for the GDPS you are using? Are you using Cvolton's GDPS code?

**Comment by WOSHIZHAZHA120** [comment]
> 介意发布您正在使用的GDPS的源代码？您是否在使用Cvolton的GDPS代码？或URL，也可以。

Yes I use Cvolton's GDPS code.

**Comment by 101arrowz** [comment]
Looks to me like [this line](https://github.com/GDColon/GDBrowser/blob/master/api/level.js#L19) is responsible, we don't send the `gameVersion` or `binaryVersion` so Cvolton's code returns data that would be parsed by a very old version of GD. If we send the proper parameters it should work. @GDColon thoughts?

**Comment by WOSHIZHAZHA120** [comment]
I think this is necessary, because many GDPS used Cvolton's code

**Comment by WOSHIZHAZHA120** [comment]
> Looks to me like [this line](https://github.com/GDColon/GDBrowser/blob/master/api/level.js#L19) is responsible, we don't send the `gameVersion` or `binaryVersion` so Cvolton's code returns data that would be parsed by a very old version of GD. If we send the proper parameters it should work. @GDColon thoughts?

And, when GDPS level used custom song, then GDBrowser will take you to NG
