### ISSUE TITLE
Bug with GDPS

### ISSUE THREAD

**Issue by WOSHIZHAZHA120** [GDColon/GDBrowser#91]
When you used cvolton's GDPS code and used GDBrowser, in search, songs unless first isn't normal.
i change some code, and i find these
![image](https://user-images.githubusercontent.com/52521836/78536120-e46eb000-781f-11ea-9084-965dd3cb3525.png)
and this is changed code
![image](https://user-images.githubusercontent.com/52521836/78536228-154ee500-7820-11ea-89a1-00756631749b.png)

**Comment by GDColon** [comment]
Please submit a pull request if you're able to fix this.
