### ISSUE TITLE
Downloading the Data of an Extreme Demon Gets Rid of its List Position

### ISSUE THREAD

**Issue by ItsMajestiX** [GDColon/GDBrowser#93]
If you try to download the additional info, the position disappears.

Before:
![image](https://user-images.githubusercontent.com/44622841/79168751-4abf7980-7db0-11ea-8de8-d9a8a6162af0.png)

After:
![image](https://user-images.githubusercontent.com/44622841/79168819-70e51980-7db0-11ea-8504-5d7ac10f7589.png)

I don't know why this is happening, as the demon download code seems to be in both level.js and download.js.

**Comment by GDColon** [comment]
I'll investigate this further. Thanks for reporting!

**Comment by GDColon** [comment]
Fixed, I literally left out a single `else`
