### ISSUE TITLE
Well, i'd like it if you could play certain levels.

### ISSUE THREAD

**Issue by D2-Players-4-Life** [GDColon/GDBrowser#98]
fsgerhgberhgbrugbreijbhebgiergnehbeerg[iowy98234yrh3ufg3rgbeubfjerfou_skeppy_is_better_than_u_make_a_yt_vid_lolei hr394y r934h r934h t935g935h gi3gn3ht9u34ht83484g0h35g0h_rec_4hr4u38 0y407yt3470ty 54yg 45g t4g4tgtgt5hg5tg

**Comment by FireRedz** [comment]
would be kinda hard to implement tbh, why? 
well you need to create an entire gd clone which in itself is pretty hard

(im not working on this code, i was saying this from spectator perspective)
