### ISSUE TITLE
stadust1971

### ISSUE THREAD

**Issue by muzikbike** [GDColon/GDBrowser#99]
I don't think that's what his name actually is.
![F06B6695-E640-49C8-B934-D8A80F093C3C](https://user-images.githubusercontent.com/52297970/83343814-33543580-a2f7-11ea-83a5-d001f9cf55d3.jpeg)
![F8F6EB1A-4DB9-43BA-95CE-E8032BE460E0](https://user-images.githubusercontent.com/52297970/83343816-36e7bc80-a2f7-11ea-8506-14fd9e23d399.png)

**Comment by GDColon** [comment]
It's his Twitter name
